version: "2"

volumes:
  xbs-db-data:

services:
  db:
    container_name: "xbs-db"
    environment:
      - "MONGO_INITDB_DATABASE=xbrowsersync"
      - "MONGO_INITDB_ROOT_PASSWORD=$XBS_DB_PASSWORD"
      - "MONGO_INITDB_ROOT_USERNAME=$XBS_DB_USERNAME"
    image: "andresvidal/rpi3-mongodb3"
    labels:
      - "traefik.enable=false"
    networks:
      - "xbs-net"
    restart: "always"
    volumes:
      - "xbs-db-data:/data/db"
      - "./mongoconfig.js:/docker-entrypoint-initdb.d/mongoconfig.js"
  api:
    container_name: "xbs-api"
    depends_on:
      - "db"
    environment:
      - "XBROWSERSYNC_DB_PWD=$XBS_DB_PASSWORD"
      - "XBROWSERSYNC_DB_USER=$XBS_DB_USERNAME"
    build:
      context: .
      dockerfile: dockerfile
    labels:
      - "traefik.frontend.rule=Host:$XBS_API_HOSTNAME"
      - "traefik.port=8080"
    networks:
      - "xbs-net"
    restart: "always"
    volumes:
      - "./settings.json:/usr/src/api/config/settings.json"
  reverse-proxy:
    command: "--api --docker"
    container_name: "xbs-reverse-proxy"
    depends_on:
      - "api"
    image: traefik:1.7.5-alpine
    labels:
      - "traefik.enable=false"
    networks:
      - "xbs-net"
    ports:
      - "443:443"
      - "80:80"
    restart: "always"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./acme.json:/acme.json"
      - "./traefik.toml:/traefik.toml"

networks:
  xbs-net: